# Generated by Django 3.1.2 on 2020-10-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('room_image', models.ImageField(upload_to='images/room/%Y/%m/%d')),
                ('type', models.CharField(choices=[('wall', 'wall'), ('floor', 'floor')], max_length=20)),
                ('reference_image', models.ImageField(upload_to='images/reference/%Y/%m/%d')),
                ('wall_mask_image', models.ImageField(blank=True, upload_to='images/wall_mask/%Y/%m/%d')),
                ('floor_mask_image', models.ImageField(blank=True, upload_to='images/floor_mask/%Y/%m/%d')),
                ('conversion_image', models.ImageField(blank=True, upload_to='images/conversion/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
