# Generated by Django 3.1.2 on 2020-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindSimilarMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('room_image', models.ImageField(upload_to='images/room/%Y/%m/%d')),
                ('type', models.CharField(choices=[('wall', 'wall'), ('floor', 'floor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Hyundai', 'Hyundai'), ('Etc', 'Etc')], max_length=20)),
                ('sub_brand', models.CharField(blank=True, max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('wall', 'wall'), ('floor', 'floor')], max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Conversion',
        ),
    ]
